on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    
jobs:
  build:
    name: build & test project
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
      
    - name: setup java env
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu' 
    
    - name: build app
      run: ./mvnw clean test
