on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  build:
    name: build , test & deploy image
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
      
    - name: setup java env
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu' 
    
    - name: test app
      run: |
        chmod a+x mvnw
        ./mvnw clean test

    - name: build & push image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: gfyhser/ab-forwarder:latest
